#!/bin/sh

#
# Created by Ken Hoo (mrkenhoo)
# Android debloater tool
# android-debloater file
# for Android 8.0 Oreo or higher
#
set -e

uninstall_packages() {
    [ ! . "${HOME}/.config/android-debloater/pkgs.conf" ] && . "${HOME}/.config/android-debloater/pkgs.conf" && \
                                                            android_user=$(adb shell cmd activity get-current-user)
    for p in "${pkgs[@]}"; do
        printf "\nRemoving package: ${p}... "
        adb shell pm uninstall --user "${android_user}" "${p}"
    done
}

check_packages() {
    for p in "${pkgs[@]}"; do
        echo "Found package: ${p}"
    done
}

help() {
    printf "Usage: ${0} [OPTIONS]

Options:
--start,-s            Begins debloating of Android devices
--check-packages,-c   Checks which packages are available for debloating
--help,-h             Prints this help\n"
}

if [ "$(whoami)" = "root" ]; then
    echo "Do not execute this script as root"
    exit 0
fi

[ -z "${1}" ] && help

while [ $# -gt 0 ]; do
    case "${1}" in
        --start|-s)
            uninstall_packages
        ;;
        --check-packages|-c)
            [ ! -d "${HOME}/.config/android-debloater" ] && mkdir "${HOME}/.config/android-debloater"
            if [ -f "${HOME}/.config/android-debloater/pkgs.conf" ]; then
                check_packages
            else
                echo ":: ERROR: ${HOME}/.config/android-debloater/pkgs.conf: No such file or directory"
                read -p "  ==> Do you want to download it? [Y/n]: " input
                case "${input}" in
                    Y|y|Yes|yes)
                        if [ -x "$(command -v curl)" ]; then
                            curl -sL "https://raw.githubusercontent.com/mrkenhoo/linux-utils/main/conf/android-debloater/pkgs.conf" > "${HOME}/.config/android-debloater/pkgs.conf"
                        elif [ -x "$(command -v wget)" ]; then
                            wget -q "https://raw.githubusercontent.com/mrkenhoo/linux-utils/main/conf/android-debloater/pkgs.conf" -O "${HOME}/.config/android-debloater/pkgs.conf"
                            else
                                echo ":: ERROR: Could not download file: curl or wget was not found"
                        fi
                        check_packages
                    ;;
                esac
            fi
        ;;

        --help|-h)
            help
        ;;

        *)
            help
        ;;
    esac
    shift
done
