#!/bin/bash

#
# Created by Ken Hoo (mrkenhoo)
# archlinux-sbct file
# A tool to enable Secure Boot on Arch Linux systems
# For Arch Linux amd64
#
set -e

if test "$(whoami)" != "root"
then
    echo "This script must be executed as root."
    exit 1
fi

if test ! "$(command -v lsb_release)"
then
    pacman -Sy lsb-release --noconfirm --needed
fi

if test "$(lsb_release -ds | sed 's,",,g')" != "Arch Linux"
then
    echo "You must be using Arch Linux to use this script."
    exit 1
fi

if test ! "$(pacman -Qqe | grep "preloader-signed")"
then
    echo "Please install the package preloader-signed from the AUR"
    exit 1
elif test "$(bootctl is-installed)" != "yes"
then
    bootctl install --no-variables
fi

find /boot/EFI/BOOT/BOOTX64.EFI -type f -exec mv -v '{}' '{}'.backup \;
find /usr/share/preloader-signed/*.efi -type f -exec cp -v '{}' /boot/EFI/BOOT/ \;
find /boot/EFI/systemd/systemd-bootx64.efi -type f -exec cp -v '{}' /boot/EFI/BOOT/loader.efi \;
find /boot/EFI/BOOT/PreLoader.efi -type f -exec mv -v '{}' /boot/EFI/BOOT/BOOTX64.EFI \;

