#!/bin/sh

#
# Created by Ken Hoo (mrkenhoo)
# chkdsk file
#

help() {
    cat << EOF

Usage: ${0} [OPTIONS]

--list-disks, -l        Shows available devices on the system
--repair-disk, -r       Sets the specified disk to be repaired
--help, -h              Shows this message

EOF
    exit
}

if [ -z "${1}" ]; then
    help
fi

while [ $# -gt 0 ]; do
    case "${1}" in
        --list-disks|-l)
            printf "\n--> These devices were found on your system:\n\n"
            `which lsblk`
            exit
        ;;

        --repair-disk|-r)
            shift
            [ ! -z "${1}" ] && disk="${1}" || echo ":: No disk was specified" && exit
        ;;

        --help|-h)
            help
        ;;

        *)
            help
        ;;
    esac
    shift
done

`which fsck` -y -f -v "${disk}"

