#!/bin/sh

# compile-kernel
# a tool made by Ken Hoo (mrkenhoo)
# for Debian GNU/Linux amd64
#
set -e

while getopts 'b:k:ch' arg
do
    case "$arg" in
        b) kernelbranch="$OPTARG";;
        k) kernelver="$OPTARG";;
        c) cleanup=1;;
        h) echo "Usage: $(basename $0) [-b KERNELBRANCH] [-k KERNEL_VERSION] [-c] {-h}"; exit 1;;
        ?) echo "Type '$(basename $0) -h' for a list of available options."; exit 1;;
    esac
done

test ! $kernelbranch && echo "Missing kernel branch" && exit 1
test ! $kernelver && echo "Missing kernel version" && exit 1

if test "$(whoami)" != "root"
then
    echo "You must execute this script as root"
    exit 1
fi

test ! "$(command -v apt)" && echo "ERROR: apt: command not found" && exit 1

if test ! -d "linux-$kernelver"
then
    echo "Downloading file linux-$kernelver.tar.xz..."
    curl -fSLO "https://cdn.kernel.org/pub/linux/kernel/$kernelbranch/linux-$kernelver.tar.xz"
    echo "Extracting linux-$kernelver.tar.gz..."
    tar xf "linux-$kernelver.tar.xz"
fi

test -d "linux-$kernelver" && cd linux-$kernelver

apt install -y flex bison libssl-dev libelf-dev

make ARCH=$(uname -m) defconfig
nice make -j `nproc --all` bindeb-pkg LOCALVERSION=-custom

test $cleanup && apt purge --autoremove flex bison libssl-dev libelf-dev

sudo update-grub && sudo update-initramfs -u -k all
