#!/bin/sh
set -e

if [ "$(whoami)" = "root" ]; then
    echo "Do not execute this script as root"
    exit
fi

help() {
    printf "\nUsage: ${0} [OPTIONS]
    
Options:
    --create-tar-file,-c        <fileName or directoryName>     Creates a tar file
    --create-gzip-tar-file,-C   <fileName or directoryName>     Creates a gzip compressed tar file
    --help,-h                                                   Show this message\n\n"
}

[ -z "${1}" ] && help && exit

while [ $# -gt 0 ]; do
    case "${1}" in
        --create-tar-file|-c)
            shift
            [ -z "${1}" ] && echo "No file or directory was specified" && exit 1
            if [ -d "${1}" ]; then
                if [ ! -f "${1}.tar" ]; then
                    echo "Creating file: ${1}.tar..."
                    tar -cf ${1}.tar ${1}
                else
                    echo "ERROR: The file ${1}.tar already exists"
                    exit
                fi
                else
                    echo ":: ERROR: Could not find the folder '${1}'"
                    exit 1
            fi
        ;;
        
        --create-gzip-tar-file|-C)
            shift
            [ -z "${1}" ] && echo "No file or directory was specified" && exit 1
            if [ ! -f "${1}.tar" ]; then
                echo "ERROR: The file ${1}.tar does not exist"
                exit 1
            elif [ -f "${1}.tar.gz" ]; then
                echo "ERROR: The file ${1}.tar.gz already exists"
                exit 1
            elif [ ! -f "${1}.tar.gz" ]; then
                echo "Creating gzip-compressed file: ${1}.tar.gz..."
                tar -zcf "${1}.tar.gz" "${1}.tar"
            fi
        ;;
        
        --clean)
            shift
            [ -z "${1}" ] && echo "No file was specified" && exit 1
            for i in ${1}.tar; do
                [ -f "${i}" ] && rm -v "${i}"
            done
            
            for i in ${1}.tar.gz; do
                [ -f "${i}" ] && rm -v "${i}"
            done
        ;;

        --help|-h)
            help
        ;;

        *)
            help
        ;;
    esac
    shift
done
