#!/bin/sh

#
# Created by Liam Powell (gfelipe099)
# Debian Deemix PyWeb Installer
# debian-dpwi file
# For Debian GNU/Linux based systems
#

pkgDir="/tmp/deemix/"
if [ -d ${pkgDir} ]; then
    echo "--> Removing previous '${pkgDir}' folder..."
    rm -r ${pkgDir}
    cd ${pkgDir}
    else
        echo "--> Creating directory..."
        mkdir -p ${pkgDir}
        cd ${pkgDir}
fi

if [ -d /usr/share/deemix-pyweb ]; then
    echo "--> Removing existing installation..."
    sudo rm -r /usr/share/deemix-pyweb
    sudo rm -r /usr/share/applications/deemix-pyweb.desktop
fi


cd ${pkgDir}

if [ -f linux-x86_64-latest.zip ]; then
    if [ ! -f /usr/bin/unzip ]; then
        echo "    ERROR: unzip: command not found"
        exit 1
        else
            echo "--> Extracting packages..."
            unzip -qqo linux-x86_64-latest.zip
    fi
    else
        echo "--> Retrieving needed packages..."
        wget -q https://download.deemix.app/pyweb/linux-x86_64-latest.zip
        if [ ! -f /usr/bin/unzip ]; then
            echo "    ERROR: unzip: command not found"
            exit 1
            else
                echo "--> Extracting packages..."
                unzip -qqo linux-x86_64-latest.zip
        fi
fi

echo "--> Installing deemix-pyweb..."
if [ ! -d /usr/share/deemix-pyweb ]; then
    echo "    Creating directory '/usr/share/deemix-pyweb'... "
    sudo mkdir -p /usr/share/deemix-pyweb
fi
printf "[Desktop Entry]
Name=Deemix
Icon=deemix-pyweb
Type=Application
Version=1.0
StartupNotify=true
Terminal=false
Path=/usr/share/deemix-pyweb
Exec=sh launch.sh
" > ${pkgDir}/deemix-pyweb.desktop
printf "#!/bin/bash\n./deemix-pyweb\n" > ${pkgDir}/launch.sh
sudo cp -dr --no-preserve=ownership ${pkgDir}/* /usr/share/deemix-pyweb
sudo install -dm 755 /usr/share/deemix-pyweb
sudo cp --no-preserve=ownership ${pkgDir}/deemix-pyweb.desktop /usr/share/deemix-pyweb/
sudo cp --no-preserve=ownership ${pkgDir}/launch.sh /usr/share/deemix-pyweb/
sudo chmod +x /usr/share/deemix-pyweb/deemix-pyweb
sudo ln -s /usr/share/deemix-pyweb/deemix-pyweb.desktop /usr/share/applications/deemix-pyweb.desktop

echo "--> Removing temporary folder '${pkgDir}'..."
sudo rm -rf ${pkgDir}

echo "--> deemix-pyweb is now installed on your system" && echo ""
