#!/usr/bin/sh

#
# A git helper script
# Made by Ken Hoo (mrkenhoo)
# gmk file
#

set -e

help() {
    cat <<EOF
Usage: ${0} [OPTIONS]

Available options are:
    --create-ssh-key        Creates an SSH key for GitHub private repositories authentication
    --status,-S             Shows the current status of the repository
    --commit,-C             Adds all the new modified files on the repository and then commits the changes
    --pull,-P               Fetches the latest changes from the repository
    --clone-repository,-c   Clones the specified repository (on private repositories it requires a verified SSH-key)
      --branch,-b           Sets the branch to clone from the repository
    --push,-p               Pushes the latest local commit to the repository
    --add,-A                Adds specified file(s) to be commited
      --label-name          Sets the label name for the tag
      --label-message       Sets the label message for the tag
    --add-tag,-a            Adds a label to the commit
    --delete-tag,-d         Deletes a label from the commit
    --show-tags,-s          Shows tags from current repository (if any)
    --help,-h               Shows this help message

EOF
}

if [ -z "${1}" ]; then
    help
fi

while [ $# -gt 0 ]; do
    case "${1}" in
        --create-ssh-key)
            if [ ! -f "$HOME/.ssh/id_ed25519" ]; then
                if [ -z "${email}" ]; then
                    read -p "Type in your email address: " email
                    echo "Press enter when prompted to save the file into the default directory"
                    ssh-keygen -t ed25519 -C "${email}"
                else
                    echo "Press enter when prompted to save the file into the default directory"
                    ssh-keygen -t ed25519 -C "${email}"
                fi
                printf "\nHere's your public SSH key:\n\n$(cat "$HOME/.ssh/id_ed25519.pub")\n\n"
            else
                echo "ERROR: $HOME/.ssh/id_ed25519: File already exists"
            fi
            exit
        ;;

        --delete-ssh-key)
            if [ -f "$HOME/.ssh/id_ed25519" ]; then
                rm -v "$HOME/.ssh/id_ed25519*"
            else
                echo "ERROR: There is nothing to delete"
            fi
        ;;

        --status|-S)
            git status .
            exit
        ;;

        --commit|-C)
            shift
            [ -z "${1}" ] && echo "No commit message provided" && exit
            git add .
            git commit -m "${1}"
            git push
            exit
        ;;

        --clone-repository|-c)
            shift
            repository="${1}"
            shift
            while [ $# -gt 0 ]; do
                case "${1}" in
                    --branch|-b)
                        shift
                        export branch="${1}"
                    ;;

                    *)
                        help
                    ;;
                esac
                shift > /dev/null 2>&1
            done
            if [ ! -z "${branch}" ]; then
                git clone git@github.com:${user_name}/"${repository}" -b "${branch}"
            else
                echo "Please specify a repository and a branch and try again"
                exit
            fi
            exit
        ;;

        --pull|-P)
            git pull
            exit
        ;;

        --push|-p)
            git push
            git push --tags
            exit
        ;;

        --add|-A)
            shift
            git add .
            exit
        ;;

        --add-tag|-a)
            shift
            while [ $# -gt 0 ]; do
                case "${1}" in
                    --label-name|-l)
                        shift
                        export label_name="${1}"
                    ;;

                    --label-message|-L)
                        shift
                        export label_message="${1}"
                    ;;

                    --help|-h)
                        help
                    ;;

                    *)
                        help
                    ;;
                esac
                shift
            done
            if [ ! -z "${label_name}" ] && [ ! -z "${label_message}" ]; then
                git tag -a "${label_name}" "${label_message}"
            else
                echo "No label name and message were provided"
            fi
            exit
        ;;

        --delete-tag|-d)
            shift
            [ ! -z "${label_name}" ] && git tag -d "${label_name}"
            echo "No label name was provided"
            exit
        ;;

        --show-tags|-s)
            git tag
            exit
        ;;

        --username)
            shift
            export user_name="${1}"
        ;;

        *)
            shift
            [ ! -z "${1}" ] && echo "ERROR: ${1}: Invalid or unknown command" || \
                echo "ERROR: No command provided"
        ;;
    esac
    shift > /dev/null 2>&1
done
