#!/bin/sh

QEMU_NVRAM_DIR="/var/lib/libvirt/qemu/nvram"

if test -z "$1"
then
    PS3=":: Select a file: "
    select nvram in ${QEMU_NVRAM_DIR}/*_VARS.fd
    do
        if test ! -f "$(echo $nvram | sed 's,.fd,_secboot.fd,g')"
        then
            virt-fw-vars --enroll-redhat -i $nvram -o $(echo $nvram | sed 's,.fd,_secboot.fd,g')
        else
            echo "error: the file $(echo $nvram | sed 's,.fd,_secboot.fd,g') already exists."
        fi
    done
elif test "$1" = "all"
then
    for nvram in ${QEMU_NVRAM_DIR}/*_VARS.fd
    do
        if test ! -f "$(echo $nvram | sed 's,.fd,_secboot.fd,g')"
        then
            virt-fw-vars --enroll-redhat -i $nvram -o $(echo $nvram | sed 's,.fd,_secboot.fd,g')
        else
            echo "error: the file $(echo $nvram | sed 's,.fd,_secboot.fd,g') already exists"
        fi
    done
fi

