#!/bin/sh

QEMU_NVRAM_DIR="/var/lib/libvirt/qemu/nvram"

PS3="Select a file: "
select nvram in ${QEMU_NVRAM_DIR}/*_VARS.fd
do
    if test ! -f "$(echo ${nvram} | sed 's,.fd,,g')_secboot.fd"
    then
        virt-fw-vars --enroll-redhat -i ${nvram} -o $(echo ${nvram} | sed 's,.fd,,g')_secboot.fd
    else
        echo "error: the file $(echo ${nvram} | sed 's,.fd,,g')_secboot.fd already exists."
    fi
done

