#!/bin/bash

#
# Created by Liam Powell (gfelipe099)
# redhat-exffsi file
# Red Hat (RHEL) exFAT filesystem installer
#

if [ "$(whoami)" != "root" ]; then
    echo "You must execute this script as root."
    exit
fi

if [ ! -d exfat/ ]; then
    git clone https://github.com/relan/exfat.git > /dev/null 2>&1
    else
        echo "Directory already exists, re-cloning from the repository..."
        rm -rf exfat/
        git clone https://github.com/relan/exfat.git > /dev/null 2>&1
fi

cd exfat

echo "Preparing installation..."
autoreconf -i > /dev/null 2>&1
./configure --prefix=/usr > /dev/null 2>&1
make > /dev/null 2>&1

echo "Installing exFAT filesystem..."
make install > /dev/null 2>&1

echo "Cleaning directory..."
make clean > /dev/null 2>&1
