#!/bin/sh
cacheDir="/home/${USER}/.cache/spotify/Data"

if [ "$(whoami)" = root ]; then
    echo "The ${USER} user is not supported. Execution aborted."
    exit
fi

if [ -d ${cacheDir} ]; then
	while true; do
		read -p "Are you sure you want to clean Spotify's cache? [Y/N]: " input
		if [ -z ${input} ]; then
			echo "You must type uppercase Y or N, in order to continue." && echo ""
		elif [ ${input} = "y" ]; then
			echo "You must type uppercase Y or N, in order to continue." && echo ""
		elif [ ${input} = "n" ]; then
			echo "You must type uppercase Y or N, in order to continue." && echo ""
		elif [ ${input} = "Y" ]; then
			echo "Cleaning Spotify cache, please wait..." && echo ""
			exit 0
		elif [ ${input} = "N" ]; then
			echo "The user cancelled the operation." && echo ""
			break
		fi
	done
	else
        echo "The cache directory does not exist or Spotify hasn't been used/installed yet."
        exit 1
fi
