#!/bin/sh
set -e

help()
{
    printf "\nUsage: ${0} [OPTIONS]

Options:
  -d    Checks mirrors based on the distro specified
  -h    Displays this message\n\n"
}

test -z $1 && help && exit 1

while getopts 'd:' arg
do
    case $arg in
        d) LINUX_DISTRO="$OPTARG";;
        ?) help && exit 1;;
    esac
done

if test -z "${LINUX_DISTRO}"
then
    echo "Missing Linux distribution"
    exit 1
fi

rate-mirrors --allow-root --save /etc/pacman.d/mirrorlist "${LINUX_DISTRO}"
