#!/bin/sh

update-mirrors() {
    if [ ! -f /usr/bin/reflector ] || [ ! -f /usr/bin/sudo ]; then
        echo ":: ERROR: reflector: unknown command"
        echo ":: ERROR: sudo: unknown command"
        echo "    --> Installing missing dependencies: reflector sudo..."
        sudo pacman -S reflector --noconfirm --needed 2>/dev/null
    fi
    if [ -z ${country} ]; then
        read -p ":: Specify a country [e.g. United States]: " input1
        country=${input1}
    fi
    if [ -z ${sortBy} ]; then
        read -p ":: Specify how to sort mirrors [age,rate,country,score,delay]: " input2
        sortBy=${input2}
    fi
    echo ":: Updating mirrors from ${country} and sorting them by ${sortBy}, please wait..."
    sudo reflector --country ${country} --sort ${sortBy} --save /etc/pacman.d/mirrorlist
}
