#!/bin/sh
set -e

help()
{
    echo "Usage: $0 [-d DISTRO]"
}

if test -z "$1"
then
    help
    exit 1
fi

while getopts 'd:' arg
do
    case $arg in
        d) LINUX_DISTRO="$OPTARG";;
        ?) help && exit 1;;
    esac
done

if test -z "${LINUX_DISTRO}"
then
    echo "Missing Linux distribution"
    exit 1
fi

rate-mirrors --allow-root --save /etc/pacman.d/mirrorlist "${LINUX_DISTRO}"
