#!/usr/bin/sh
set -e

help() {
    echo "Usage: $(basename "$0") [-d FOLDER]"
}

while getopts 'dhv:' arg
do
    case "$arg" in
        d) download_dir="$OPTARG";;
        h) help;;
	v) set -v;;
        ?) help;;
    esac
done

if test -z "${download_dir}"
then
    help
    exit 1
else
    cd "${download_dir}"
fi

if test -x "$(command -v curl)"
then
    test -f virtio-stable.iso && test -f virtio-latest.iso && \
        echo "==> Removing old ISO images..." && \
            rm -v virtio-stable.iso virtio-latest.iso

    echo "==> Fetching the latest virtio-win ISO..."
    curl --progress-bar -fSLO \
        https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

    echo "==> Fetching the stable virtio-win ISO..."
    curl --progress-bar -fSL \
        https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso \
	-o virtio-win-stable.iso
else
    echo ":: ERROR: curl: command not found"
    exit 1
fi

