#!/usr/bin/sh
set -e

help() {
    printf "\nUsage: `basename $0` [OPTIONS]

Options:
    -d   Specifies the directory to where the ISOs will be downloaded to
    -h   Displays this message\n\n"
}

while getopts 'vd:' arg
do
    case "$arg" in
        d) download_dir="$OPTARG";;
        h) help;;
	v) set -v;;
        ?) help;;
    esac
done

test -z "$download_dir" && help && exit 1

if test -x "`command -v curl`"
then
    test -f $download_dir/virtio-stable.iso && test -f $download_dir/virtio-latest.iso && \
        echo "==> Removing old ISO images..." && \
            rm -iv ${download_dir}/virtio-stable.iso ${download_dir}/virtio-latest.iso

    echo "==> Fetching the latest virtio-win ISO..."
    curl -fSLO \
        https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

    echo "==> Fetching the stable virtio-win ISO..."
    curl -fSLO \
        https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso
else
    echo ":: ERROR: curl: command not found"
    exit 1
fi

