#!/bin/sh
set -e

if test ! $disk
then
    lsblk && read -p "Select your installation disk: " disk
fi

echo "The selected disk: $disk, will be formatted and all of it's data will be lost."
read -p "Do you want to continue? [Y/N]: " confirm
case "$confirm" in
    [Nn]*) echo "The user cancelled the operation"; exit 1;;
esac

if `grep -qo /mnt/$codename /proc/mounts`
then
    umount -v -A -R /mnt/$codename
fi

sgdisk -Z $disk
sgdisk -a 2048 -o $disk
partprobe $disk
sgdisk -n 1::+100M --typecode=1:ef00 --change-name=1:EFI ${disk}
sgdisk -n 2::+500M --typecode=2:8300 --change-name=2:boot ${disk}
sgdisk -n 3::-1 --typecode=3:8300 --change-name=3:root ${disk}

if test `grep -qo nvme $disk`
then
    mkfs.ext4 -L root ${disk}p3
    mkfs.ext4 -L BOOT ${disk}p2
    mkfs.vfat -F 32 -n EFI ${disk}p1
else
    mkfs.ext4 -L root ${disk}3
    mkfs.ext4 -L BOOT ${disk}2
    mkfs.vfat -F 32 -n EFI ${disk}1
fi

mount -v ${disk}3 /mnt/$codename

for d in /mnt/$codename/{boot,home}
do
    if test ! -d "$d"
    then
        mkdir -v $d/{boot,home}
    fi
done

mount -v ${disk}2 /mnt/$codename/boot

if test ! -d /mnt/$codename/boot/efi
then
    mkdir -v /mnt/$codename
fi

sudo mount -v ${disk}1 /mnt/$codename/boot/efi

for i in /dev /dev/pts /proc /sys /sys/firmware/efi/efivars /run
do
    sudo mount -v -B $i /mnt/${codename}$i
done

