#!/bin/sh

if test ! $no_formatting
then
    if test -d "$chroot_dir/$codename"
    then
        sudo chroot "$chroot_dir/$codename" \
             /bin/bash -c "export LANG=C;
echo 'deb http://archive.ubuntu.com/ubuntu $codename main universe restricted multiverse' | tee /etc/apt/sources.list;
echo 'deb http://archive.ubuntu.com/ubuntu $codename-security main universe restricted multiverse' | tee -a /etc/apt/sources.list;
echo 'deb http://archive.ubuntu.com/ubuntu $codename-backports main universe restricted multiverse' | tee -a /etc/apt/sources.list;
apt update && apt full-upgrade -y && apt install -y xubuntu-core"
    else
        sudo chroot "/mnt/$codename" \
            /bin/bash -c "export LANG=C;
echo 'deb http://archive.ubuntu.com/ubuntu $codename main universe restricted multiverse' | tee /etc/apt/sources.list;
echo 'deb http://archive.ubuntu.com/ubuntu $codename-security main universe restricted multiverse' | tee -a /etc/apt/sources.list;
echo 'deb http://archive.ubuntu.com/ubuntu $codename-backports main universe restricted multiverse' | tee -a /etc/apt/sources.list;
apt update && apt full-upgrade -y && apt install -y xubuntu-core"
    fi
fi

